# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
open_collective: blitzjs
custom: ['https://paypal.me/thebayers?locale.x=en_US']
