name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
# categories:
#   - title: 'Blitz'
#     label: 'blitz'
#   - title: '@blitzjs/next'
#     label: 'blitz-next'
#   - title: '@blitzjs/rpc'
#     label: 'blitz-rpc'
#   - title: '@blitzjs/auth'
#     label: 'blitz-auth'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
# autolabeler:
#   - label: 'blitz'
#     title:
#      - '/blitz/i'
#   - label: 'blitz-next'
#     title:
#       - '/@blitzjs\/next/i'
#   - label: 'blitz-rpc'
#     title:
#       - '/@blitzjs\/rpc/i'
#   - label: 'blitz-auth'
#     title:
#       - '/@blitzjs\/auth/i'
template: |
  ## What’s Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
