import {NextScript} from "next/document"
import React from "react"
import {BlitzData} from "./blitz-data"

export type BlitzScriptProps = {
  /** nonce property to pass to the <script> element generated by Blitz. */
  nonce?: string
  /** crossOrigin property to pass to the <script> element generated by Blitz. */
  crossOrigin?: string
}

export function BlitzScript({nonce, crossOrigin}: BlitzScriptProps) {
  return (
    <>
      <BlitzData />
      <NextScript nonce={nonce} crossOrigin={crossOrigin} />
    </>
  )
}
