blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/blitz-js/blitz/discussions/new
    about: Ask questions and discuss with other community members
